# Generated by Django 4.2.4 on 2023-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('discountReceived', models.IntegerField(blank=True)),
                ('fromWhichAccount', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Payrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('commission', models.IntegerField(blank=True)),
                ('AwardsReceived', models.IntegerField(blank=True)),
                ('fromWhichAccount', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('fromWhichAccount', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
        ),
    ]
