# Generated by Django 4.2.4 on 2023-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_payrol_awardsreceived_alter_payrol_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='discountReceived',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fromWhichAccount',
        ),
        migrations.RemoveField(
            model_name='payrol',
            name='fromWhichAccount',
        ),
        migrations.AddField(
            model_name='expense',
            name='toWho',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
