# Generated by Django 4.2.4 on 2023-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_discountreceived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrol',
            name='AwardsReceived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='commission',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='description',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
