# Generated by Django 4.2.4 on 2023-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_payrol_awardsreceived_alter_payrol_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='AwardsReceived',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payrol',
            name='commission',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prepaidexpense',
            name='amount',
            field=models.FloatField(),
        ),
    ]
