# Generated by Django 4.2.4 on 2023-09-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartsofaccounts',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
