# Generated by Django 4.2.4 on 2023-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('purchasePrice', models.IntegerField(blank=True, default=0)),
                ('ActualPurchasePrice', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('measurementUnit', models.CharField(blank=True, max_length=150)),
                ('discountReceived', models.IntegerField(blank=True, default=0)),
                ('salePrice', models.IntegerField(blank=True, default=0)),
                ('ActualSalePrice', models.IntegerField(blank=True, default=0)),
                ('discountGiven', models.IntegerField(blank=True, default=0)),
                ('expectedLifespan', models.IntegerField(blank=True, default=0)),
                ('currentValue', models.IntegerField(blank=True, default=0)),
                ('monthlyFees', models.IntegerField(blank=True, default=0)),
                ('discarded', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
        ),
    ]
