# Generated by Django 4.2.4 on 2023-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='type',
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='forSale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventoryType',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventory',
            name='leased',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
