# Generated by Django 4.2.4 on 2023-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_inventory_code_alter_inventory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.FloatField(default=0.0)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
