# Generated by Django 4.2.4 on 2023-09-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitAmount', models.IntegerField(default=0)),
                ('toWho', models.CharField(blank=True)),
                ('fromWhichAccount', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('totalLoanPayable', models.IntegerField()),
                ('installment', models.IntegerField()),
                ('installmentPaymentDuration', models.CharField(max_length=150)),
                ('dayTaken', models.CharField(max_length=120)),
                ('paidUntil', models.CharField(max_length=120)),
                ('toWhichAccount', models.CharField(max_length=120)),
                ('fromWho', models.CharField(blank=True, max_length=200)),
                ('interestPaidUpfront', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitAmount', models.IntegerField(default=0)),
                ('creditAmount', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200)),
                ('toWhichAccount', models.CharField(blank=True)),
                ('fromWhichAccount', models.CharField(blank=True)),
                ('toWho', models.CharField(blank=True)),
                ('fromWho', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('chartsOfAccounts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.chartsofaccounts')),
            ],
        ),
    ]
