# Generated by Django 4.2.4 on 2023-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_remove_transaction_type_loan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='costOfGoodSold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creditAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debitAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='interestPaidUpfront',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paidComplete',
            field=models.BooleanField(blank=True),
        ),
    ]
