# Generated by Django 4.2.4 on 2023-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_transaction_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paidComplete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
