# Generated by Django 4.2.4 on 2023-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_transaction_paidcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalwithdrawal',
            name='debitAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='extraCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='installment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='totalLoanPayable',
            field=models.FloatField(),
        ),
    ]
