# Generated by Django 4.2.4 on 2023-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_alter_capitalwithdrawal_debitamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='extraCost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
