# Generated by Django 4.2.4 on 2023-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_alter_loan_extracost'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loanBalance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
