# Generated by Django 4.2.4 on 2023-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_loan_loanbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='chartsOfAccounts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='costOfGoodSold',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creditAmount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debitAmount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='forWhat',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fromWhichAccount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fromWho',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='interestPaidUpfront',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='toWhichAccount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='toWho',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
