# Generated by Django 4.2.4 on 2023-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_alter_transaction_chartsofaccounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalwithdrawal',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
